import { BoardConfig } from "./interfaces";

export const daisy: BoardConfig = {
  cols: 10,
  rows: 11,
  target: [
    { col: 9, row: 10 },
    { col: 10, row: 10 },
    { col: 9, row: 11 },
    { col: 10, row: 11 },
  ],
  master: [
    { row: 4, col: 5 },
    { row: 4, col: 6 },
    { row: 5, col: 5 },
    { row: 5, col: 6 },
  ],
  movables: [
    [
      { row: 4, col: 4 },
      { row: 5, col: 4 },
    ],
    [
      { row: 4, col: 7 },
      { row: 5, col: 7 },
    ],
    [{ row: 6, col: 4 }],
    [{ row: 6, col: 5 }],
    [{ row: 6, col: 6 }],
    [{ row: 6, col: 7 }],
    [{ row: 7, col: 4 }],
    [{ row: 7, col: 5 }],
    [{ row: 7, col: 6 }],
    [{ row: 7, col: 7 }],
    [{ row: 8, col: 4 }],
    [{ row: 8, col: 7 }],
  ],
  walls: [
    [
      { row: 9, col: 4 },
      { row: 9, col: 3 },
      { row: 8, col: 3 },
      { row: 7, col: 3 },
      { row: 6, col: 3 },
      { row: 5, col: 3 },
      { row: 4, col: 3 },
      { row: 3, col: 3 },
      { row: 3, col: 4 },
      { row: 3, col: 5 },
      { row: 3, col: 6 },
      { row: 3, col: 7 },
      { row: 3, col: 8 },
      { row: 4, col: 8 },
      { row: 5, col: 8 },
      { row: 6, col: 8 },
      { row: 7, col: 8 },
      { row: 8, col: 8 },
      { row: 9, col: 8 },
      { row: 9, col: 7 },
    ],
  ],
  destructibles: [
    [
      { row: 9, col: 5 },
      { row: 9, col: 6 },
    ],
  ],
};

export const violet: BoardConfig = {
  rows: 11,
  cols: 10,
  target: [
    { row: 10, col: 9 },
    { row: 10, col: 10 },
    { row: 11, col: 9 },
    { row: 11, col: 10 },
  ],
  master: [
    { row: 4, col: 5 },
    { row: 4, col: 6 },
    { row: 5, col: 5 },
    { row: 5, col: 6 },
  ],
  movables: [
    [
      { row: 4, col: 4 },
      { row: 5, col: 4 },
    ],
    [
      { row: 4, col: 7 },
      { row: 5, col: 7 },
    ],
    [
      { row: 6, col: 4 },
      { row: 7, col: 4 },
    ],
    [{ row: 6, col: 5 }],
    [{ row: 6, col: 6 }],
    [{ row: 6, col: 7 }],
    [{ row: 7, col: 5 }],
    [{ row: 7, col: 6 }],
    [{ row: 7, col: 7 }],
    [{ row: 8, col: 4 }],
    [{ row: 8, col: 7 }],
  ],
  walls: [
    [
      { row: 9, col: 4 },
      { row: 9, col: 3 },
      { row: 8, col: 3 },
      { row: 7, col: 3 },
      { row: 6, col: 3 },
      { row: 5, col: 3 },
      { row: 4, col: 3 },
      { row: 3, col: 3 },
      { row: 3, col: 4 },
      { row: 3, col: 5 },
      { row: 3, col: 6 },
      { row: 3, col: 7 },
      { row: 3, col: 8 },
      { row: 4, col: 8 },
      { row: 5, col: 8 },
      { row: 6, col: 8 },
      { row: 7, col: 8 },
      { row: 8, col: 8 },
      { row: 9, col: 8 },
      { row: 9, col: 7 },
    ],
  ],
  destructibles: [
    [
      { row: 9, col: 5 },
      { row: 9, col: 6 },
    ],
  ],
};

export const poppy: BoardConfig = {
  rows: 11,
  cols: 10,
  target: [
    { row: 10, col: 9 },
    { row: 10, col: 10 },
    { row: 11, col: 9 },
    { row: 11, col: 10 },
  ],
  master: [
    { row: 4, col: 5 },
    { row: 4, col: 6 },
    { row: 5, col: 5 },
    { row: 5, col: 6 },
  ],
  movables: [
    [
      { row: 4, col: 4 },
      { row: 5, col: 4 },
    ],
    [
      { row: 4, col: 7 },
      { row: 5, col: 7 },
    ],
    [{ row: 6, col: 4 }],
    [
      { row: 6, col: 5 },
      { row: 6, col: 6 },
    ],
    [{ row: 6, col: 7 }],
    [{ row: 7, col: 4 }],
    [{ row: 7, col: 5 }],
    [{ row: 7, col: 6 }],
    [{ row: 7, col: 7 }],
    [{ row: 8, col: 4 }],
    [{ row: 8, col: 7 }],
  ],
  walls: [
    [
      { row: 9, col: 4 },
      { row: 9, col: 3 },
      { row: 8, col: 3 },
      { row: 7, col: 3 },
      { row: 6, col: 3 },
      { row: 5, col: 3 },
      { row: 4, col: 3 },
      { row: 3, col: 3 },
      { row: 3, col: 4 },
      { row: 3, col: 5 },
      { row: 3, col: 6 },
      { row: 3, col: 7 },
      { row: 3, col: 8 },
      { row: 4, col: 8 },
      { row: 5, col: 8 },
      { row: 6, col: 8 },
      { row: 7, col: 8 },
      { row: 8, col: 8 },
      { row: 9, col: 8 },
      { row: 9, col: 7 },
    ],
  ],
  destructibles: [
    [
      { row: 9, col: 5 },
      { row: 9, col: 6 },
    ],
  ],
};

export const pansy: BoardConfig = {
  rows: 11,
  cols: 10,
  target: [
    { row: 10, col: 9 },
    { row: 10, col: 10 },
    { row: 11, col: 9 },
    { row: 11, col: 10 },
  ],
  master: [
    { row: 4, col: 5 },
    { row: 4, col: 6 },
    { row: 5, col: 5 },
    { row: 5, col: 6 },
  ],
  movables: [
    [
      { row: 4, col: 4 },
      { row: 5, col: 4 },
    ],
    [
      { row: 4, col: 7 },
      { row: 5, col: 7 },
    ],
    [
      { row: 6, col: 4 },
      { row: 7, col: 4 },
    ],
    [{ row: 6, col: 5 }],
    [{ row: 6, col: 6 }],
    [
      { row: 6, col: 7 },
      { row: 7, col: 7 },
    ],
    [{ row: 7, col: 5 }],
    [{ row: 7, col: 6 }],
    [{ row: 8, col: 4 }],
    [{ row: 8, col: 7 }],
  ],
  walls: [
    [
      { row: 9, col: 4 },
      { row: 9, col: 3 },
      { row: 8, col: 3 },
      { row: 7, col: 3 },
      { row: 6, col: 3 },
      { row: 5, col: 3 },
      { row: 4, col: 3 },
      { row: 3, col: 3 },
      { row: 3, col: 4 },
      { row: 3, col: 5 },
      { row: 3, col: 6 },
      { row: 3, col: 7 },
      { row: 3, col: 8 },
      { row: 4, col: 8 },
      { row: 5, col: 8 },
      { row: 6, col: 8 },
      { row: 7, col: 8 },
      { row: 8, col: 8 },
      { row: 9, col: 8 },
      { row: 9, col: 7 },
    ],
  ],
  destructibles: [
    [
      { row: 9, col: 5 },
      { row: 9, col: 6 },
    ],
  ],
};

export const snowdrop: BoardConfig = {
  rows: 11,
  cols: 10,
  target: [
    { row: 10, col: 9 },
    { row: 10, col: 10 },
    { row: 11, col: 9 },
    { row: 11, col: 10 },
  ],
  master: [
    { row: 4, col: 5 },
    { row: 4, col: 6 },
    { row: 5, col: 5 },
    { row: 5, col: 6 },
  ],
  movables: [
    [
      { row: 4, col: 4 },
      { row: 5, col: 4 },
    ],
    [
      { row: 4, col: 7 },
      { row: 5, col: 7 },
    ],
    [
      { row: 6, col: 4 },
      { row: 7, col: 4 },
    ],
    [
      { row: 6, col: 5 },
      { row: 6, col: 6 },
    ],
    [{ row: 6, col: 7 }],
    [{ row: 7, col: 5 }],
    [{ row: 7, col: 6 }],
    [{ row: 7, col: 7 }],
    [{ row: 8, col: 4 }],
    [{ row: 8, col: 7 }],
  ],
  walls: [
    [
      { row: 9, col: 4 },
      { row: 9, col: 3 },
      { row: 8, col: 3 },
      { row: 7, col: 3 },
      { row: 6, col: 3 },
      { row: 5, col: 3 },
      { row: 4, col: 3 },
      { row: 3, col: 3 },
      { row: 3, col: 4 },
      { row: 3, col: 5 },
      { row: 3, col: 6 },
      { row: 3, col: 7 },
      { row: 3, col: 8 },
      { row: 4, col: 8 },
      { row: 5, col: 8 },
      { row: 6, col: 8 },
      { row: 7, col: 8 },
      { row: 8, col: 8 },
      { row: 9, col: 8 },
      { row: 9, col: 7 },
    ],
  ],
  destructibles: [
    [
      { row: 9, col: 5 },
      { row: 9, col: 6 },
    ],
  ],
};

export const forgetMeNot: BoardConfig = {
  rows: 11,
  cols: 10,
  target: [
    { row: 10, col: 9 },
    { row: 10, col: 10 },
    { row: 11, col: 9 },
    { row: 11, col: 10 },
  ],
  master: [
    { row: 4, col: 5 },
    { row: 4, col: 6 },
    { row: 5, col: 5 },
    { row: 5, col: 6 },
  ],
  movables: [
    [
      { row: 4, col: 4 },
      { row: 5, col: 4 },
    ],
    [
      { row: 4, col: 7 },
      { row: 5, col: 7 },
    ],
    [
      { row: 6, col: 4 },
      { row: 7, col: 4 },
    ],
    [
      { row: 6, col: 5 },
      { row: 6, col: 6 },
    ],
    [
      { row: 6, col: 7 },
      { row: 7, col: 7 },
    ],
    [{ row: 7, col: 5 }],
    [{ row: 7, col: 6 }],
    [{ row: 8, col: 4 }],
    [{ row: 8, col: 7 }],
  ],
  walls: [
    [
      { row: 9, col: 4 },
      { row: 9, col: 3 },
      { row: 8, col: 3 },
      { row: 7, col: 3 },
      { row: 6, col: 3 },
      { row: 5, col: 3 },
      { row: 4, col: 3 },
      { row: 3, col: 3 },
      { row: 3, col: 4 },
      { row: 3, col: 5 },
      { row: 3, col: 6 },
      { row: 3, col: 7 },
      { row: 3, col: 8 },
      { row: 4, col: 8 },
      { row: 5, col: 8 },
      { row: 6, col: 8 },
      { row: 7, col: 8 },
      { row: 8, col: 8 },
      { row: 9, col: 8 },
      { row: 9, col: 7 },
    ],
  ],
  destructibles: [
    [
      { row: 9, col: 5 },
      { row: 9, col: 6 },
    ],
  ],
};

export const agatka: BoardConfig = {
  rows: 9,
  cols: 11,
  target: [
    { row: 8, col: 1 },
    { row: 8, col: 2 },
    { row: 9, col: 1 },
  ],
  master: [
    { row: 4, col: 4 },
    { row: 4, col: 5 },
    { row: 5, col: 4 },
  ],
  movables: [
    [{ row: 1, col: 1 }],
    [{ row: 2, col: 1 }],
    [
      { row: 1, col: 2 },
      { row: 1, col: 3 },
      { row: 1, col: 4 },
      { row: 1, col: 5 },
      { row: 2, col: 2 },
      { row: 2, col: 3 },
      { row: 2, col: 4 },
      { row: 2, col: 5 },
    ],
    [
      { row: 1, col: 6 },
      { row: 1, col: 7 },
      { row: 1, col: 8 },
      { row: 1, col: 9 },
      { row: 1, col: 10 },
    ],
    [{ row: 1, col: 11 }],
    [
      { row: 2, col: 6 },
      { row: 2, col: 7 },
      { row: 2, col: 8 },
    ],
    [
      { row: 2, col: 10 },
      { row: 2, col: 11 },
    ],
    [{ row: 3, col: 10 }],
    [
      { row: 5, col: 1 },
      { row: 6, col: 1 },
    ],
    [
      { row: 3, col: 2 },
      { row: 4, col: 2 },
      { row: 5, col: 2 },
      { row: 6, col: 2 },
      { row: 7, col: 2 },
      { row: 8, col: 2 },
      { row: 9, col: 2 },
    ],
    [
      { row: 9, col: 3 },
      { row: 9, col: 4 },
    ],
    [{ row: 8, col: 5 }],
    [{ row: 9, col: 7 }],
    [{ row: 8, col: 9 }],
    [
      { row: 4, col: 6 },
      { row: 4, col: 7 },
    ],
    [{ row: 4, col: 8 }],
    [
      { row: 5, col: 5 },
      { row: 5, col: 6 },
    ],
    [{ row: 5, col: 7 }],
    [{ row: 5, col: 8 }],
    [{ row: 6, col: 4 }],
    [{ row: 6, col: 5 }],
    [{ row: 6, col: 6 }],
  ],
  walls: [
    [
      { row: 3, col: 7 },
      { row: 3, col: 6 },
      { row: 3, col: 5 },
      { row: 3, col: 4 },
      { row: 3, col: 3 },
      { row: 4, col: 3 },
      { row: 5, col: 3 },
      { row: 6, col: 3 },
      { row: 7, col: 3 },
      { row: 7, col: 4 },
      { row: 7, col: 5 },
      { row: 7, col: 6 },
      { row: 7, col: 7 },
      { row: 7, col: 8 },
      { row: 7, col: 9 },
      { row: 6, col: 9 },
      { row: 5, col: 9 },
    ],
  ],
  destructibles: [
    [
      { row: 3, col: 8 },
      { row: 3, col: 9 },
      { row: 4, col: 9 },
    ],
  ],
};

export const doggie: BoardConfig = {
  rows: 15,
  cols: 18,
  target: [
    { row: 1, col: 1 },
    { row: 1, col: 2 },
    { row: 2, col: 2 },
    { row: 3, col: 1 },
    { row: 3, col: 2 },
    { row: 3, col: 3 },
    { row: 3, col: 4 },
    { row: 4, col: 3 },
    { row: 4, col: 4 },
  ],
  master: [
    { row: 6, col: 7 },
    { row: 6, col: 8 },
    { row: 7, col: 8 },
    { row: 8, col: 7 },
    { row: 8, col: 8 },
    { row: 8, col: 9 },
    { row: 8, col: 10 },
    { row: 9, col: 9 },
    { row: 9, col: 10 },
  ],
  movables: [
    [{ row: 6, col: 6 }],
    [
      { row: 7, col: 6 },
      { row: 7, col: 7 },
    ],
    [{ row: 8, col: 6 }],
    [{ row: 9, col: 6 }],
    [{ row: 9, col: 7 }],
    [{ row: 9, col: 8 }],
    [{ row: 10, col: 6 }],
    [{ row: 10, col: 7 }],
    [{ row: 10, col: 8 }],
    [
      { row: 6, col: 9 },
      { row: 7, col: 9 },
    ],
    [
      { row: 6, col: 10 },
      { row: 6, col: 11 },
      { row: 6, col: 12 },
    ],
    [{ row: 6, col: 13 }],
    [{ row: 7, col: 10 }],
    [{ row: 7, col: 11 }],
    [{ row: 7, col: 12 }],
    [{ row: 7, col: 13 }],
    [{ row: 8, col: 11 }],
    [{ row: 8, col: 12 }],
    [{ row: 8, col: 13 }],
    [{ row: 9, col: 11 }],
    [{ row: 9, col: 12 }],
    [{ row: 9, col: 13 }],
  ],
  walls: [
    [
      { row: 11, col: 11 },
      { row: 11, col: 10 },
      { row: 11, col: 9 },
      { row: 11, col: 8 },
      { row: 11, col: 7 },
      { row: 11, col: 6 },
      { row: 11, col: 5 },
      { row: 10, col: 5 },
      { row: 9, col: 5 },
      { row: 8, col: 5 },
      { row: 7, col: 5 },
      { row: 6, col: 5 },
      { row: 5, col: 5 },
      { row: 5, col: 6 },
      { row: 5, col: 7 },
      { row: 5, col: 8 },
      { row: 5, col: 9 },
      { row: 5, col: 10 },
      { row: 5, col: 11 },
      { row: 5, col: 12 },
      { row: 5, col: 13 },
      { row: 5, col: 14 },
      { row: 6, col: 14 },
      { row: 7, col: 14 },
      { row: 8, col: 14 },
      { row: 9, col: 14 },
    ],
  ],
  destructibles: [
    [
      { row: 10, col: 14 },
      { row: 11, col: 14 },
      { row: 11, col: 13 },
      { row: 11, col: 12 },
    ],
  ],
};

export const success: BoardConfig = {
  rows: 8,
  cols: 11,
  target: [
    { row: 1, col: 1 },
    { row: 1, col: 2 },
  ],
  master: [
    { row: 3, col: 4 },
    { row: 3, col: 5 },
  ],
  movables: [
    [
      { row: 4, col: 1 },
      { row: 4, col: 2 },
      { row: 5, col: 1 },
      { row: 5, col: 2 },
    ],
    [{ row: 1, col: 11 }],
    [
      { row: 3, col: 6 },
      { row: 3, col: 7 },
    ],
    [{ row: 3, col: 8 }],
    [{ row: 4, col: 4 }],
    [{ row: 4, col: 5 }],
    [{ row: 4, col: 6 }],
    [
      { row: 4, col: 7 },
      { row: 5, col: 7 },
    ],
    [
      { row: 4, col: 8 },
      { row: 5, col: 8 },
    ],
    [{ row: 5, col: 4 }],
    [{ row: 5, col: 5 }],
    [
      { row: 5, col: 6 },
      { row: 6, col: 6 },
    ],
    [
      { row: 6, col: 4 },
      { row: 6, col: 5 },
    ],
  ],
  walls: [
    [
      { row: 6, col: 9 },
      { row: 7, col: 9 },
      { row: 7, col: 8 },
      { row: 7, col: 7 },
      { row: 7, col: 6 },
      { row: 7, col: 5 },
      { row: 7, col: 4 },
      { row: 7, col: 3 },
      { row: 6, col: 3 },
      { row: 5, col: 3 },
      { row: 4, col: 3 },
      { row: 3, col: 3 },
      { row: 2, col: 3 },
      { row: 2, col: 4 },
      { row: 2, col: 5 },
      { row: 2, col: 6 },
      { row: 2, col: 7 },
      { row: 2, col: 8 },
      { row: 2, col: 9 },
      { row: 3, col: 9 },
      { row: 4, col: 9 },
    ],
  ],
  destructibles: [[{ row: 5, col: 9 }]],
};

export const bone: BoardConfig = {
  rows: 12,
  cols: 8,
  target: [
    { row: 1, col: 1 },
    { row: 2, col: 1 },
    { row: 3, col: 1 },
  ],
  master: [
    { row: 5, col: 6 },
    { row: 6, col: 6 },
    { row: 7, col: 6 },
  ],
  movables: [
    [{ row: 3, col: 2 }],
    [{ row: 5, col: 3 }],
    [{ row: 5, col: 4 }],
    [{ row: 5, col: 5 }],
    [
      { row: 6, col: 4 },
      { row: 6, col: 5 },
    ],
    [
      { row: 7, col: 4 },
      { row: 7, col: 5 },
    ],
    [{ row: 8, col: 4 }],
    [{ row: 8, col: 5 }],
    [{ row: 8, col: 6 }],
  ],
  walls: [
    [
      { row: 9, col: 3 },
      { row: 9, col: 2 },
      { row: 8, col: 2 },
      { row: 7, col: 2 },
      { row: 6, col: 2 },
      { row: 5, col: 2 },
      { row: 4, col: 2 },
      { row: 4, col: 3 },
      { row: 4, col: 4 },
      { row: 4, col: 5 },
      { row: 4, col: 6 },
      { row: 4, col: 7 },
      { row: 5, col: 7 },
      { row: 6, col: 7 },
      { row: 7, col: 7 },
      { row: 8, col: 7 },
      { row: 9, col: 7 },
      { row: 9, col: 6 },
      { row: 9, col: 5 },
    ],
  ],
  destructibles: [[{ row: 9, col: 4 }]],
};

export const fortune: BoardConfig = {
  rows: 14,
  cols: 10,
  target: [
    { row: 1, col: 1 },
    { row: 1, col: 2 },
    { row: 2, col: 1 },
    { row: 3, col: 1 },
  ],
  master: [
    { row: 8, col: 4 },
    { row: 8, col: 5 },
    { row: 9, col: 4 },
    { row: 10, col: 4 },
  ],
  movables: [
    [
      { row: 1, col: 8 },
      { row: 1, col: 9 },
      { row: 1, col: 10 },
    ],
    [
      { row: 3, col: 5 },
      { row: 3, col: 6 },
      { row: 3, col: 7 },
    ],
    [{ row: 5, col: 4 }],
    [{ row: 5, col: 5 }],
    [
      { row: 6, col: 4 },
      { row: 6, col: 5 },
      { row: 7, col: 4 },
      { row: 7, col: 5 },
    ],
    [
      { row: 6, col: 6 },
      { row: 7, col: 6 },
    ],
    [
      { row: 8, col: 6 },
      { row: 8, col: 7 },
    ],
    [{ row: 9, col: 5 }],
    [{ row: 9, col: 6 }],
    [
      { row: 9, col: 7 },
      { row: 10, col: 7 },
    ],
    [
      { row: 10, col: 5 },
      { row: 10, col: 6 },
    ],
    [
      { row: 11, col: 1 },
      { row: 12, col: 1 },
    ],
    [
      { row: 10, col: 10 },
      { row: 11, col: 10 },
      { row: 12, col: 10 },
    ],
    [{ row: 14, col: 2 }],
  ],
  walls: [
    [
      { row: 4, col: 6 },
      { row: 4, col: 5 },
      { row: 4, col: 4 },
      { row: 4, col: 3 },
      { row: 5, col: 3 },
      { row: 6, col: 3 },
      { row: 7, col: 3 },
      { row: 8, col: 3 },
      { row: 9, col: 3 },
      { row: 10, col: 3 },
      { row: 11, col: 3 },
      { row: 11, col: 4 },
      { row: 11, col: 5 },
      { row: 11, col: 6 },
      { row: 11, col: 7 },
      { row: 11, col: 8 },
      { row: 10, col: 8 },
      { row: 9, col: 8 },
      { row: 8, col: 8 },
      { row: 7, col: 8 },
      { row: 6, col: 8 },
    ],
  ],
  destructibles: [
    [
      { row: 4, col: 7 },
      { row: 4, col: 8 },
      { row: 5, col: 8 },
    ],
  ],
};

export const fool: BoardConfig = {
  rows: 8,
  cols: 12,
  target: [
    { row: 1, col: 1 },
    { row: 1, col: 2 },
  ],
  master: [
    { row: 6, col: 8 },
    { row: 6, col: 9 },
  ],
  movables: [
    [{ row: 1, col: 4 }],
    [
      { row: 2, col: 1 },
      { row: 2, col: 2 },
    ],
    [
      { row: 3, col: 4 },
      { row: 3, col: 5 },
      { row: 4, col: 4 },
      { row: 4, col: 5 },
    ],
    [
      { row: 3, col: 6 },
      { row: 4, col: 6 },
    ],
    [{ row: 3, col: 7 }],
    [{ row: 4, col: 7 }],
    [{ row: 5, col: 4 }],
    [{ row: 5, col: 5 }],
    [
      { row: 5, col: 6 },
      { row: 5, col: 7 },
    ],
    [
      { row: 4, col: 8 },
      { row: 5, col: 8 },
    ],
    [
      { row: 4, col: 9 },
      { row: 5, col: 9 },
    ],
    [{ row: 6, col: 4 }],
    [{ row: 6, col: 5 }],
    [
      { row: 6, col: 6 },
      { row: 6, col: 7 },
    ],
  ],
  walls: [
    [
      { row: 2, col: 3 },
      { row: 2, col: 4 },
      { row: 2, col: 5 },
      { row: 2, col: 6 },
      { row: 2, col: 7 },
      { row: 2, col: 8 },
      { row: 2, col: 9 },
      { row: 2, col: 10 },
      { row: 3, col: 10 },
      { row: 4, col: 10 },
      { row: 5, col: 10 },
      { row: 6, col: 10 },
      { row: 7, col: 10 },
      { row: 7, col: 9 },
      { row: 7, col: 8 },
      { row: 7, col: 7 },
      { row: 7, col: 6 },
      { row: 7, col: 5 },
      { row: 7, col: 4 },
      { row: 7, col: 3 },
      { row: 6, col: 3 },
      { row: 5, col: 3 },
      { row: 4, col: 3 },
    ],
  ],
  destructibles: [[{ row: 3, col: 3 }]],
};

export const solomon: BoardConfig = {
  rows: 11,
  cols: 11,
  target: [
    { row: 1, col: 2 },
    { row: 2, col: 1 },
    { row: 2, col: 2 },
  ],
  master: [
    { row: 7, col: 8 },
    { row: 8, col: 7 },
    { row: 8, col: 8 },
  ],
  movables: [
    [{ row: 1, col: 3 }],
    [
      { row: 4, col: 6 },
      { row: 4, col: 7 },
    ],
    [
      { row: 4, col: 8 },
      { row: 5, col: 8 },
    ],
    [
      { row: 5, col: 5 },
      { row: 6, col: 5 },
    ],
    [{ row: 5, col: 6 }],
    [{ row: 6, col: 6 }],
    [
      { row: 5, col: 7 },
      { row: 6, col: 7 },
    ],
    [{ row: 6, col: 8 }],
    [
      { row: 6, col: 4 },
      { row: 7, col: 4 },
      { row: 8, col: 4 },
    ],
    [{ row: 7, col: 5 }],
    [{ row: 7, col: 6 }],
    [{ row: 7, col: 7 }],
    [
      { row: 8, col: 5 },
      { row: 8, col: 6 },
    ],
  ],
  walls: [
    [
      { row: 3, col: 3 },
      { row: 4, col: 3 },
    ],
    [
      { row: 3, col: 6 },
      { row: 3, col: 7 },
      { row: 3, col: 8 },
      { row: 3, col: 9 },
      { row: 4, col: 9 },
      { row: 5, col: 9 },
      { row: 6, col: 9 },
      { row: 7, col: 9 },
      { row: 8, col: 9 },
      { row: 9, col: 9 },
      { row: 9, col: 8 },
      { row: 9, col: 7 },
      { row: 9, col: 6 },
      { row: 9, col: 5 },
      { row: 9, col: 4 },
      { row: 9, col: 3 },
      { row: 8, col: 3 },
      { row: 7, col: 3 },
      { row: 6, col: 3 },
    ],
  ],
  destructibles: [
    [
      { row: 3, col: 4 },
      { row: 3, col: 5 },
    ],
    [{ row: 5, col: 3 }],
  ],
};

export const kleopatra: BoardConfig = {
  rows: 10,
  cols: 10,
  target: [
    { row: 1, col: 1 },
    { row: 1, col: 2 },
    { row: 2, col: 2 },
  ],
  master: [
    { row: 5, col: 4 },
    { row: 5, col: 5 },
    { row: 6, col: 5 },
  ],
  movables: [
    [
      { row: 1, col: 6 },
      { row: 1, col: 7 },
    ],
    [
      { row: 1, col: 10 },
      { row: 2, col: 10 },
      { row: 3, col: 10 },
      { row: 4, col: 10 },
    ],
    [{ row: 5, col: 1 }],
    [{ row: 6, col: 10 }],
    [
      { row: 9, col: 1 },
      { row: 9, col: 2 },
      { row: 10, col: 1 },
      { row: 10, col: 2 },
    ],
    [
      { row: 9, col: 9 },
      { row: 9, col: 10 },
      { row: 10, col: 9 },
      { row: 10, col: 10 },
    ],
    [{ row: 4, col: 4 }],
    [{ row: 4, col: 5 }],
    [{ row: 4, col: 6 }],
    [{ row: 4, col: 7 }],
    [
      { row: 5, col: 6 },
      { row: 5, col: 7 },
    ],
    [
      { row: 6, col: 4 },
      { row: 7, col: 4 },
    ],
    [{ row: 7, col: 5 }],
    [{ row: 6, col: 6 }],
    [{ row: 7, col: 7 }],
  ],
  walls: [
    [
      { row: 8, col: 6 },
      { row: 8, col: 5 },
      { row: 8, col: 4 },
      { row: 8, col: 3 },
      { row: 7, col: 3 },
      { row: 6, col: 3 },
      { row: 5, col: 3 },
      { row: 4, col: 3 },
      { row: 3, col: 3 },
      { row: 3, col: 4 },
      { row: 3, col: 5 },
      { row: 3, col: 6 },
      { row: 3, col: 7 },
      { row: 3, col: 8 },
      { row: 4, col: 8 },
      { row: 5, col: 8 },
      { row: 6, col: 8 },
    ],
  ],
  destructibles: [
    [
      { row: 8, col: 7 },
      { row: 8, col: 8 },
      { row: 7, col: 8 },
    ],
  ],
};

export const shark: BoardConfig = {
  rows: 12,
  cols: 14,
  target: [
    { row: 1, col: 1 },
    { row: 1, col: 2 },
    { row: 1, col: 3 },
    { row: 2, col: 2 },
  ],
  master: [
    { row: 7, col: 5 },
    { row: 7, col: 6 },
    { row: 7, col: 7 },
    { row: 8, col: 6 },
  ],
  movables: [
    [{ row: 2, col: 8 }],
    [
      { row: 1, col: 10 },
      { row: 1, col: 11 },
      { row: 2, col: 10 },
      { row: 2, col: 11 },
    ],
    [
      { row: 4, col: 13 },
      { row: 4, col: 14 },
    ],
    [
      { row: 7, col: 1 },
      { row: 8, col: 1 },
      { row: 9, col: 1 },
      { row: 10, col: 1 },
      { row: 11, col: 1 },
      { row: 12, col: 1 },
    ],
    [{ row: 4, col: 5 }],
    [{ row: 4, col: 6 }],
    [
      { row: 5, col: 5 },
      { row: 5, col: 6 },
    ],
    [
      { row: 4, col: 7 },
      { row: 5, col: 7 },
    ],
    [
      { row: 4, col: 8 },
      { row: 4, col: 9 },
      { row: 5, col: 8 },
      { row: 5, col: 9 },
    ],
    [{ row: 4, col: 10 }],
    [{ row: 5, col: 10 }],
    [
      { row: 6, col: 5 },
      { row: 6, col: 6 },
    ],
    [{ row: 6, col: 7 }],
    [
      { row: 6, col: 8 },
      { row: 7, col: 8 },
    ],
    [{ row: 6, col: 9 }],
    [{ row: 7, col: 9 }],
    [
      { row: 6, col: 10 },
      { row: 7, col: 10 },
    ],
    [
      { row: 8, col: 5 },
      { row: 9, col: 5 },
    ],
    [
      { row: 9, col: 6 },
      { row: 9, col: 7 },
    ],
    [{ row: 8, col: 7 }],
    [{ row: 8, col: 8 }],
    [{ row: 9, col: 9 }],
    [{ row: 8, col: 10 }],
  ],
  walls: [
    [
      { row: 6, col: 11 },
      { row: 7, col: 11 },
      { row: 8, col: 11 },
      { row: 9, col: 11 },
      { row: 10, col: 11 },
      { row: 10, col: 10 },
      { row: 10, col: 9 },
      { row: 10, col: 8 },
      { row: 10, col: 7 },
      { row: 10, col: 6 },
      { row: 10, col: 5 },
      { row: 10, col: 4 },
      { row: 9, col: 4 },
      { row: 8, col: 4 },
      { row: 7, col: 4 },
      { row: 6, col: 4 },
      { row: 5, col: 4 },
      { row: 4, col: 4 },
      { row: 3, col: 4 },
      { row: 3, col: 5 },
      { row: 3, col: 6 },
      { row: 3, col: 7 },
      { row: 3, col: 8 },
      { row: 3, col: 9 },
      { row: 3, col: 10 },
      { row: 3, col: 11 },
    ],
  ],
  destructibles: [
    [
      { row: 4, col: 11 },
      { row: 5, col: 11 },
    ],
  ],
};

export const rome: BoardConfig = {
  rows: 12,
  cols: 14,
  target: [
    { row: 1, col: 1 },
    { row: 1, col: 2 },
    { row: 1, col: 3 },
    { row: 2, col: 2 },
  ],
  master: [
    { row: 7, col: 5 },
    { row: 7, col: 6 },
    { row: 7, col: 7 },
    { row: 8, col: 6 },
  ],
  movables: [
    [{ row: 2, col: 8 }],
    [
      { row: 1, col: 10 },
      { row: 1, col: 11 },
      { row: 2, col: 10 },
      { row: 2, col: 11 },
    ],
    [
      { row: 4, col: 13 },
      { row: 4, col: 14 },
    ],
    [
      { row: 7, col: 1 },
      { row: 8, col: 1 },
      { row: 9, col: 1 },
      { row: 10, col: 1 },
      { row: 11, col: 1 },
      { row: 12, col: 1 },
    ],
    [{ row: 4, col: 5 }],
    [{ row: 4, col: 6 }],
    [
      { row: 5, col: 5 },
      { row: 5, col: 6 },
    ],
    [
      { row: 4, col: 7 },
      { row: 5, col: 7 },
    ],
    [
      { row: 4, col: 8 },
      { row: 4, col: 9 },
      { row: 5, col: 8 },
      { row: 5, col: 9 },
    ],
    [{ row: 4, col: 10 }],
    [{ row: 5, col: 10 }],
    [
      { row: 6, col: 5 },
      { row: 6, col: 6 },
    ],
    [{ row: 6, col: 7 }],
    [
      { row: 6, col: 8 },
      { row: 7, col: 8 },
    ],
    [{ row: 6, col: 9 }],
    [{ row: 7, col: 9 }],
    [
      { row: 6, col: 10 },
      { row: 7, col: 10 },
    ],
    [
      { row: 8, col: 5 },
      { row: 9, col: 5 },
    ],
    [
      { row: 9, col: 6 },
      { row: 9, col: 7 },
    ],
    [{ row: 8, col: 7 }],
    [{ row: 8, col: 8 }],
    [{ row: 9, col: 9 }],
    [{ row: 8, col: 10 }],
  ],
  walls: [
    [
      { row: 6, col: 11 },
      { row: 7, col: 11 },
      { row: 8, col: 11 },
      { row: 9, col: 11 },
      { row: 10, col: 11 },
      { row: 10, col: 10 },
      { row: 10, col: 9 },
      { row: 10, col: 8 },
      { row: 10, col: 7 },
      { row: 10, col: 6 },
      { row: 10, col: 5 },
      { row: 10, col: 4 },
      { row: 9, col: 4 },
      { row: 8, col: 4 },
      { row: 7, col: 4 },
      { row: 6, col: 4 },
      { row: 5, col: 4 },
      { row: 4, col: 4 },
      { row: 3, col: 4 },
      { row: 3, col: 5 },
      { row: 3, col: 6 },
      { row: 3, col: 7 },
      { row: 3, col: 8 },
      { row: 3, col: 9 },
      { row: 3, col: 10 },
      { row: 3, col: 11 },
    ],
  ],
  destructibles: [
    [
      { row: 4, col: 11 },
      { row: 5, col: 11 },
    ],
  ],
};

export const sunshine: BoardConfig = {
  rows: 27,
  cols: 27,
  target: [
    { row: 1, col: 13 },
    { row: 1, col: 14 },
    { row: 1, col: 15 },
    { row: 2, col: 12 },
    { row: 2, col: 13 },
    { row: 2, col: 15 },
    { row: 2, col: 16 },
    { row: 3, col: 12 },
    { row: 3, col: 16 },
    { row: 4, col: 12 },
    { row: 4, col: 13 },
    { row: 4, col: 15 },
    { row: 4, col: 16 },
    { row: 5, col: 13 },
    { row: 5, col: 14 },
    { row: 5, col: 15 },
  ],
  master: [
    { row: 7, col: 13 },
    { row: 7, col: 14 },
    { row: 7, col: 15 },
    { row: 8, col: 12 },
    { row: 8, col: 13 },
    { row: 8, col: 15 },
    { row: 8, col: 16 },
    { row: 9, col: 12 },
    { row: 9, col: 16 },
    { row: 10, col: 12 },
    { row: 10, col: 13 },
    { row: 10, col: 15 },
    { row: 10, col: 16 },
    { row: 11, col: 13 },
    { row: 11, col: 14 },
    { row: 11, col: 15 },
  ],
  movables: [
    [
      { row: 1, col: 1 },
      { row: 1, col: 2 },
      { row: 2, col: 1 },
      { row: 2, col: 2 },
    ],
    [
      { row: 1, col: 3 },
      { row: 2, col: 3 },
    ],
    [
      { row: 1, col: 4 },
      { row: 1, col: 5 },
      { row: 2, col: 4 },
      { row: 2, col: 5 },
    ],
    [
      { row: 3, col: 1 },
      { row: 3, col: 2 },
    ],
    [
      { row: 3, col: 4 },
      { row: 3, col: 5 },
    ],
    [
      { row: 4, col: 1 },
      { row: 4, col: 2 },
      { row: 5, col: 1 },
      { row: 5, col: 2 },
    ],
    [
      { row: 4, col: 3 },
      { row: 5, col: 3 },
    ],
    [
      { row: 4, col: 4 },
      { row: 4, col: 5 },
      { row: 5, col: 4 },
      { row: 5, col: 5 },
    ],
    [
      { row: 1, col: 6 },
      { row: 1, col: 7 },
      { row: 1, col: 8 },
      { row: 1, col: 9 },
      { row: 1, col: 10 },
      { row: 2, col: 6 },
      { row: 2, col: 7 },
      { row: 2, col: 8 },
      { row: 2, col: 9 },
      { row: 2, col: 10 },
      { row: 3, col: 6 },
      { row: 3, col: 7 },
      { row: 3, col: 8 },
      { row: 3, col: 9 },
      { row: 3, col: 10 },
      { row: 4, col: 6 },
      { row: 4, col: 7 },
      { row: 4, col: 8 },
      { row: 4, col: 9 },
      { row: 4, col: 10 },
      { row: 5, col: 6 },
      { row: 5, col: 7 },
      { row: 5, col: 8 },
      { row: 5, col: 9 },
      { row: 5, col: 10 },
    ],
    [
      { row: 1, col: 12 },
      { row: 1, col: 13 },
      { row: 2, col: 12 },
      { row: 2, col: 13 },
    ],
    [
      { row: 1, col: 14 },
      { row: 2, col: 14 },
    ],
    [
      { row: 1, col: 15 },
      { row: 1, col: 16 },
      { row: 2, col: 15 },
      { row: 2, col: 16 },
    ],
    [
      { row: 3, col: 12 },
      { row: 3, col: 13 },
    ],
    [
      { row: 3, col: 15 },
      { row: 3, col: 16 },
    ],
    [
      { row: 4, col: 12 },
      { row: 4, col: 13 },
      { row: 5, col: 12 },
      { row: 5, col: 13 },
    ],
    [
      { row: 4, col: 14 },
      { row: 5, col: 14 },
    ],
    [
      { row: 4, col: 15 },
      { row: 4, col: 16 },
      { row: 5, col: 15 },
      { row: 5, col: 16 },
    ],
    [
      { row: 1, col: 18 },
      { row: 1, col: 19 },
      { row: 1, col: 20 },
      { row: 1, col: 21 },
      { row: 1, col: 22 },
      { row: 2, col: 18 },
      { row: 2, col: 19 },
      { row: 2, col: 20 },
      { row: 2, col: 21 },
      { row: 2, col: 22 },
      { row: 3, col: 18 },
      { row: 3, col: 19 },
      { row: 3, col: 20 },
      { row: 3, col: 21 },
      { row: 3, col: 22 },
      { row: 4, col: 18 },
      { row: 4, col: 19 },
      { row: 4, col: 20 },
      { row: 4, col: 21 },
      { row: 4, col: 22 },
      { row: 5, col: 18 },
      { row: 5, col: 19 },
      { row: 5, col: 20 },
      { row: 5, col: 21 },
      { row: 5, col: 22 },
    ],
    [
      { row: 1, col: 23 },
      { row: 1, col: 24 },
      { row: 2, col: 23 },
      { row: 2, col: 24 },
    ],
    [
      { row: 1, col: 25 },
      { row: 2, col: 25 },
    ],
    [
      { row: 1, col: 26 },
      { row: 1, col: 27 },
      { row: 2, col: 26 },
      { row: 2, col: 27 },
    ],
    [
      { row: 3, col: 23 },
      { row: 3, col: 24 },
    ],
    [
      { row: 3, col: 26 },
      { row: 3, col: 27 },
    ],
    [
      { row: 4, col: 23 },
      { row: 4, col: 24 },
      { row: 5, col: 23 },
      { row: 5, col: 24 },
    ],
    [
      { row: 4, col: 25 },
      { row: 5, col: 25 },
    ],
    [
      { row: 4, col: 26 },
      { row: 4, col: 27 },
      { row: 5, col: 26 },
      { row: 5, col: 27 },
    ],
    [
      { row: 6, col: 1 },
      { row: 6, col: 2 },
      { row: 6, col: 3 },
      { row: 6, col: 4 },
      { row: 6, col: 5 },
      { row: 7, col: 1 },
      { row: 7, col: 2 },
      { row: 7, col: 3 },
      { row: 7, col: 4 },
      { row: 7, col: 5 },
      { row: 8, col: 1 },
      { row: 8, col: 2 },
      { row: 8, col: 3 },
      { row: 8, col: 4 },
      { row: 8, col: 5 },
      { row: 9, col: 1 },
      { row: 9, col: 2 },
      { row: 9, col: 3 },
      { row: 9, col: 4 },
      { row: 9, col: 5 },
      { row: 10, col: 1 },
      { row: 10, col: 2 },
      { row: 10, col: 3 },
      { row: 10, col: 4 },
      { row: 10, col: 5 },
    ],
    [
      { row: 6, col: 23 },
      { row: 6, col: 24 },
      { row: 6, col: 25 },
      { row: 6, col: 26 },
      { row: 6, col: 27 },
      { row: 7, col: 23 },
      { row: 7, col: 24 },
      { row: 7, col: 25 },
      { row: 7, col: 26 },
      { row: 7, col: 27 },
      { row: 8, col: 23 },
      { row: 8, col: 24 },
      { row: 8, col: 25 },
      { row: 8, col: 26 },
      { row: 8, col: 27 },
      { row: 9, col: 23 },
      { row: 9, col: 24 },
      { row: 9, col: 25 },
      { row: 9, col: 26 },
      { row: 9, col: 27 },
      { row: 10, col: 23 },
      { row: 10, col: 24 },
      { row: 10, col: 25 },
      { row: 10, col: 26 },
      { row: 10, col: 27 },
    ],
    [
      { row: 12, col: 1 },
      { row: 12, col: 2 },
      { row: 13, col: 1 },
      { row: 13, col: 2 },
    ],
    [
      { row: 12, col: 3 },
      { row: 13, col: 3 },
    ],
    [
      { row: 12, col: 4 },
      { row: 12, col: 5 },
      { row: 13, col: 4 },
      { row: 13, col: 5 },
    ],
    [
      { row: 14, col: 1 },
      { row: 14, col: 2 },
    ],
    [
      { row: 14, col: 4 },
      { row: 14, col: 5 },
    ],
    [
      { row: 15, col: 1 },
      { row: 15, col: 2 },
      { row: 16, col: 1 },
      { row: 16, col: 2 },
    ],
    [
      { row: 15, col: 3 },
      { row: 16, col: 3 },
    ],
    [
      { row: 15, col: 4 },
      { row: 15, col: 5 },
      { row: 16, col: 4 },
      { row: 16, col: 5 },
    ],
    [
      { row: 12, col: 23 },
      { row: 12, col: 24 },
      { row: 13, col: 23 },
      { row: 13, col: 24 },
    ],
    [
      { row: 12, col: 25 },
      { row: 13, col: 25 },
    ],
    [
      { row: 12, col: 26 },
      { row: 12, col: 27 },
      { row: 13, col: 26 },
      { row: 13, col: 27 },
    ],
    [
      { row: 14, col: 23 },
      { row: 14, col: 24 },
    ],
    [
      { row: 14, col: 26 },
      { row: 14, col: 27 },
    ],
    [
      { row: 15, col: 23 },
      { row: 15, col: 24 },
      { row: 16, col: 23 },
      { row: 16, col: 24 },
    ],
    [
      { row: 15, col: 25 },
      { row: 16, col: 25 },
    ],
    [
      { row: 15, col: 26 },
      { row: 15, col: 27 },
      { row: 16, col: 26 },
      { row: 16, col: 27 },
    ],
    [
      { row: 18, col: 1 },
      { row: 18, col: 2 },
      { row: 18, col: 3 },
      { row: 18, col: 4 },
      { row: 18, col: 5 },
      { row: 19, col: 1 },
      { row: 19, col: 2 },
      { row: 19, col: 3 },
      { row: 19, col: 4 },
      { row: 19, col: 5 },
      { row: 20, col: 1 },
      { row: 20, col: 2 },
      { row: 20, col: 3 },
      { row: 20, col: 4 },
      { row: 20, col: 5 },
      { row: 21, col: 1 },
      { row: 21, col: 2 },
      { row: 21, col: 3 },
      { row: 21, col: 4 },
      { row: 21, col: 5 },
      { row: 22, col: 1 },
      { row: 22, col: 2 },
      { row: 22, col: 3 },
      { row: 22, col: 4 },
      { row: 22, col: 5 },
    ],
    [
      { row: 18, col: 23 },
      { row: 18, col: 24 },
      { row: 18, col: 25 },
      { row: 18, col: 26 },
      { row: 18, col: 27 },
      { row: 19, col: 23 },
      { row: 19, col: 24 },
      { row: 19, col: 25 },
      { row: 19, col: 26 },
      { row: 19, col: 27 },
      { row: 20, col: 23 },
      { row: 20, col: 24 },
      { row: 20, col: 25 },
      { row: 20, col: 26 },
      { row: 20, col: 27 },
      { row: 21, col: 23 },
      { row: 21, col: 24 },
      { row: 21, col: 25 },
      { row: 21, col: 26 },
      { row: 21, col: 27 },
      { row: 22, col: 23 },
      { row: 22, col: 24 },
      { row: 22, col: 25 },
      { row: 22, col: 26 },
      { row: 22, col: 27 },
    ],
    [
      { row: 23, col: 1 },
      { row: 23, col: 2 },
      { row: 24, col: 1 },
      { row: 24, col: 2 },
    ],
    [
      { row: 23, col: 3 },
      { row: 24, col: 3 },
    ],
    [
      { row: 23, col: 4 },
      { row: 23, col: 5 },
      { row: 24, col: 4 },
      { row: 24, col: 5 },
    ],
    [
      { row: 25, col: 1 },
      { row: 25, col: 2 },
    ],
    [
      { row: 25, col: 4 },
      { row: 25, col: 5 },
    ],
    [
      { row: 26, col: 1 },
      { row: 26, col: 2 },
      { row: 27, col: 1 },
      { row: 27, col: 2 },
    ],
    [
      { row: 26, col: 3 },
      { row: 27, col: 3 },
    ],
    [
      { row: 26, col: 4 },
      { row: 26, col: 5 },
      { row: 27, col: 4 },
      { row: 27, col: 5 },
    ],
    [
      { row: 23, col: 6 },
      { row: 23, col: 7 },
      { row: 23, col: 8 },
      { row: 23, col: 9 },
      { row: 23, col: 10 },
      { row: 24, col: 6 },
      { row: 24, col: 7 },
      { row: 24, col: 8 },
      { row: 24, col: 9 },
      { row: 24, col: 10 },
      { row: 25, col: 6 },
      { row: 25, col: 7 },
      { row: 25, col: 8 },
      { row: 25, col: 9 },
      { row: 25, col: 10 },
      { row: 26, col: 6 },
      { row: 26, col: 7 },
      { row: 26, col: 8 },
      { row: 26, col: 9 },
      { row: 26, col: 10 },
      { row: 27, col: 6 },
      { row: 27, col: 7 },
      { row: 27, col: 8 },
      { row: 27, col: 9 },
      { row: 27, col: 10 },
    ],
    [
      { row: 23, col: 12 },
      { row: 23, col: 13 },
      { row: 24, col: 12 },
      { row: 24, col: 13 },
    ],
    [
      { row: 23, col: 14 },
      { row: 24, col: 14 },
    ],
    [
      { row: 23, col: 15 },
      { row: 23, col: 16 },
      { row: 24, col: 15 },
      { row: 24, col: 16 },
    ],
    [
      { row: 25, col: 12 },
      { row: 25, col: 13 },
    ],
    [
      { row: 25, col: 15 },
      { row: 25, col: 16 },
    ],
    [
      { row: 26, col: 12 },
      { row: 26, col: 13 },
      { row: 27, col: 12 },
      { row: 27, col: 13 },
    ],
    [
      { row: 26, col: 14 },
      { row: 27, col: 14 },
    ],
    [
      { row: 26, col: 15 },
      { row: 26, col: 16 },
      { row: 27, col: 15 },
      { row: 27, col: 16 },
    ],
    [
      { row: 23, col: 18 },
      { row: 23, col: 19 },
      { row: 23, col: 20 },
      { row: 23, col: 21 },
      { row: 23, col: 22 },
      { row: 24, col: 18 },
      { row: 24, col: 19 },
      { row: 24, col: 20 },
      { row: 24, col: 21 },
      { row: 24, col: 22 },
      { row: 25, col: 18 },
      { row: 25, col: 19 },
      { row: 25, col: 20 },
      { row: 25, col: 21 },
      { row: 25, col: 22 },
      { row: 26, col: 18 },
      { row: 26, col: 19 },
      { row: 26, col: 20 },
      { row: 26, col: 21 },
      { row: 26, col: 22 },
      { row: 27, col: 18 },
      { row: 27, col: 19 },
      { row: 27, col: 20 },
      { row: 27, col: 21 },
      { row: 27, col: 22 },
    ],
    [
      { row: 23, col: 23 },
      { row: 23, col: 24 },
      { row: 24, col: 23 },
      { row: 24, col: 24 },
    ],
    [
      { row: 23, col: 25 },
      { row: 24, col: 25 },
    ],
    [
      { row: 23, col: 26 },
      { row: 23, col: 27 },
      { row: 24, col: 26 },
      { row: 24, col: 27 },
    ],
    [
      { row: 25, col: 23 },
      { row: 25, col: 24 },
    ],
    [
      { row: 25, col: 26 },
      { row: 25, col: 27 },
    ],
    [
      { row: 26, col: 23 },
      { row: 26, col: 24 },
      { row: 27, col: 23 },
      { row: 27, col: 24 },
    ],
    [
      { row: 26, col: 25 },
      { row: 27, col: 25 },
    ],
    [
      { row: 26, col: 26 },
      { row: 26, col: 27 },
      { row: 27, col: 26 },
      { row: 27, col: 27 },
    ],
    [
      { row: 7, col: 7 },
      { row: 7, col: 8 },
      { row: 8, col: 7 },
      { row: 8, col: 8 },
    ],
    [
      { row: 7, col: 9 },
      { row: 8, col: 9 },
    ],
    [
      { row: 7, col: 10 },
      { row: 7, col: 11 },
      { row: 8, col: 10 },
      { row: 8, col: 11 },
    ],
    [
      { row: 9, col: 7 },
      { row: 9, col: 8 },
    ],
    [{ row: 9, col: 9 }],
    [
      { row: 9, col: 10 },
      { row: 9, col: 11 },
    ],
    [
      { row: 10, col: 7 },
      { row: 10, col: 8 },
      { row: 11, col: 7 },
      { row: 11, col: 8 },
    ],
    [
      { row: 10, col: 9 },
      { row: 11, col: 9 },
    ],
    [
      { row: 10, col: 10 },
      { row: 10, col: 11 },
      { row: 11, col: 10 },
      { row: 11, col: 11 },
    ],
    [{ row: 7, col: 12 }],
    [{ row: 7, col: 16 }],
    [{ row: 9, col: 14 }],
    [{ row: 11, col: 12 }],
    [{ row: 11, col: 16 }],
    [
      { row: 7, col: 17 },
      { row: 7, col: 18 },
      { row: 8, col: 17 },
      { row: 8, col: 18 },
    ],
    [
      { row: 7, col: 19 },
      { row: 8, col: 19 },
    ],
    [
      { row: 7, col: 20 },
      { row: 7, col: 21 },
      { row: 8, col: 20 },
      { row: 8, col: 21 },
    ],
    [
      { row: 9, col: 17 },
      { row: 9, col: 18 },
    ],
    [{ row: 9, col: 19 }],
    [
      { row: 9, col: 20 },
      { row: 9, col: 21 },
    ],
    [
      { row: 10, col: 17 },
      { row: 10, col: 18 },
      { row: 11, col: 17 },
      { row: 11, col: 18 },
    ],
    [
      { row: 10, col: 19 },
      { row: 11, col: 19 },
    ],
    [
      { row: 10, col: 20 },
      { row: 10, col: 21 },
      { row: 11, col: 20 },
      { row: 11, col: 21 },
    ],
    [
      { row: 12, col: 7 },
      { row: 12, col: 8 },
      { row: 12, col: 9 },
      { row: 12, col: 10 },
      { row: 12, col: 11 },
      { row: 13, col: 7 },
      { row: 13, col: 8 },
      { row: 13, col: 9 },
      { row: 13, col: 10 },
      { row: 13, col: 11 },
      { row: 14, col: 7 },
      { row: 14, col: 8 },
      { row: 14, col: 9 },
      { row: 14, col: 10 },
      { row: 14, col: 11 },
      { row: 15, col: 7 },
      { row: 15, col: 8 },
      { row: 15, col: 9 },
      { row: 15, col: 10 },
      { row: 15, col: 11 },
      { row: 16, col: 7 },
      { row: 16, col: 8 },
      { row: 16, col: 9 },
      { row: 16, col: 10 },
      { row: 16, col: 11 },
    ],
    [
      { row: 12, col: 12 },
      { row: 12, col: 13 },
      { row: 13, col: 12 },
      { row: 13, col: 13 },
    ],
    [
      { row: 12, col: 14 },
      { row: 13, col: 14 },
    ],
    [
      { row: 12, col: 15 },
      { row: 12, col: 16 },
      { row: 13, col: 15 },
      { row: 13, col: 16 },
    ],
    [
      { row: 14, col: 12 },
      { row: 14, col: 13 },
    ],
    [
      { row: 14, col: 15 },
      { row: 14, col: 16 },
    ],
    [
      { row: 15, col: 12 },
      { row: 15, col: 13 },
      { row: 16, col: 12 },
      { row: 16, col: 13 },
    ],
    [
      { row: 15, col: 14 },
      { row: 16, col: 14 },
    ],
    [
      { row: 15, col: 15 },
      { row: 15, col: 16 },
      { row: 16, col: 15 },
      { row: 16, col: 16 },
    ],
    [
      { row: 12, col: 17 },
      { row: 12, col: 18 },
      { row: 12, col: 19 },
      { row: 12, col: 20 },
      { row: 12, col: 21 },
      { row: 13, col: 17 },
      { row: 13, col: 18 },
      { row: 13, col: 19 },
      { row: 13, col: 20 },
      { row: 13, col: 21 },
      { row: 14, col: 17 },
      { row: 14, col: 18 },
      { row: 14, col: 19 },
      { row: 14, col: 20 },
      { row: 14, col: 21 },
      { row: 15, col: 17 },
      { row: 15, col: 18 },
      { row: 15, col: 19 },
      { row: 15, col: 20 },
      { row: 15, col: 21 },
      { row: 16, col: 17 },
      { row: 16, col: 18 },
      { row: 16, col: 19 },
      { row: 16, col: 20 },
      { row: 16, col: 21 },
    ],
    [
      { row: 17, col: 7 },
      { row: 17, col: 8 },
      { row: 18, col: 7 },
      { row: 18, col: 8 },
    ],
    [{ row: 17, col: 9 }],
    [{ row: 18, col: 9 }],
    [
      { row: 17, col: 10 },
      { row: 17, col: 11 },
      { row: 18, col: 10 },
      { row: 18, col: 11 },
    ],
    [{ row: 19, col: 7 }],
    [{ row: 19, col: 8 }],
    [{ row: 19, col: 9 }],
    [{ row: 19, col: 10 }],
    [{ row: 19, col: 11 }],
    [
      { row: 20, col: 7 },
      { row: 20, col: 8 },
      { row: 21, col: 7 },
      { row: 21, col: 8 },
    ],
    [{ row: 20, col: 9 }],
    [{ row: 21, col: 9 }],
    [
      { row: 20, col: 10 },
      { row: 20, col: 11 },
      { row: 21, col: 10 },
      { row: 21, col: 11 },
    ],
    [
      { row: 17, col: 12 },
      { row: 17, col: 13 },
      { row: 18, col: 12 },
      { row: 18, col: 13 },
    ],
    [{ row: 17, col: 14 }],
    [
      { row: 17, col: 15 },
      { row: 17, col: 16 },
      { row: 18, col: 15 },
      { row: 18, col: 16 },
    ],
    [{ row: 19, col: 12 }],
    [{ row: 19, col: 14 }],
    [{ row: 19, col: 16 }],
    [
      { row: 20, col: 12 },
      { row: 20, col: 13 },
      { row: 21, col: 12 },
      { row: 21, col: 13 },
    ],
    [{ row: 21, col: 14 }],
    [
      { row: 20, col: 15 },
      { row: 20, col: 16 },
      { row: 21, col: 15 },
      { row: 21, col: 16 },
    ],
    [
      { row: 17, col: 17 },
      { row: 17, col: 18 },
      { row: 18, col: 17 },
      { row: 18, col: 18 },
    ],
    [{ row: 17, col: 19 }],
    [{ row: 18, col: 19 }],
    [
      { row: 17, col: 20 },
      { row: 17, col: 21 },
      { row: 18, col: 20 },
      { row: 18, col: 21 },
    ],
    [{ row: 19, col: 17 }],
    [{ row: 19, col: 18 }],
    [{ row: 19, col: 19 }],
    [{ row: 19, col: 20 }],
    [{ row: 19, col: 21 }],
    [
      { row: 20, col: 17 },
      { row: 20, col: 18 },
      { row: 21, col: 17 },
      { row: 21, col: 18 },
    ],
    [{ row: 20, col: 19 }],
    [{ row: 21, col: 19 }],
    [
      { row: 20, col: 20 },
      { row: 20, col: 21 },
      { row: 21, col: 20 },
      { row: 21, col: 21 },
    ],
  ],
  walls: [
    [
      { row: 22, col: 11 },
      { row: 22, col: 10 },
      { row: 22, col: 9 },
      { row: 22, col: 8 },
      { row: 22, col: 7 },
      { row: 22, col: 6 },
      { row: 21, col: 6 },
      { row: 20, col: 6 },
      { row: 19, col: 6 },
      { row: 18, col: 6 },
      { row: 17, col: 6 },
      { row: 16, col: 6 },
      { row: 15, col: 6 },
      { row: 14, col: 6 },
      { row: 13, col: 6 },
      { row: 12, col: 6 },
      { row: 11, col: 6 },
      { row: 10, col: 6 },
      { row: 9, col: 6 },
      { row: 8, col: 6 },
      { row: 7, col: 6 },
      { row: 6, col: 6 },
      { row: 6, col: 7 },
      { row: 6, col: 8 },
      { row: 6, col: 9 },
      { row: 6, col: 10 },
      { row: 6, col: 11 },
      { row: 6, col: 12 },
      { row: 6, col: 13 },
      { row: 6, col: 14 },
      { row: 6, col: 15 },
      { row: 6, col: 16 },
      { row: 6, col: 17 },
      { row: 6, col: 18 },
      { row: 6, col: 19 },
      { row: 6, col: 20 },
      { row: 6, col: 21 },
      { row: 6, col: 22 },
      { row: 7, col: 22 },
      { row: 8, col: 22 },
      { row: 9, col: 22 },
      { row: 10, col: 22 },
      { row: 11, col: 22 },
      { row: 12, col: 22 },
      { row: 13, col: 22 },
      { row: 14, col: 22 },
      { row: 15, col: 22 },
      { row: 16, col: 22 },
      { row: 17, col: 22 },
      { row: 18, col: 22 },
      { row: 19, col: 22 },
      { row: 20, col: 22 },
      { row: 21, col: 22 },
      { row: 22, col: 22 },
      { row: 22, col: 21 },
      { row: 22, col: 20 },
      { row: 22, col: 19 },
      { row: 22, col: 18 },
      { row: 22, col: 17 },
    ],
  ],
  destructibles: [
    [
      { row: 22, col: 12 },
      { row: 22, col: 13 },
      { row: 22, col: 14 },
      { row: 22, col: 15 },
      { row: 22, col: 16 },
    ],
  ],
};
